"""
KAIROS Future Engine — deterministic operational intelligence over real KAIROS data.

Everything here is computed from the tickets / activity_logs tables plus the configured campus
topology (campus_graph.py). No numbers are generated by an LLM and nothing is invented:
when data is insufficient the result says so explicitly.
"""
import hashlib
import hmac
import secrets
import threading
import time
from collections import Counter, defaultdict
from datetime import datetime, timedelta, timezone
from typing import Any, Dict, List, Optional

from .campus_graph import (
    BUILDING_IMPACT,
    BUILDINGS,
    CATEGORY_SERVICE,
    SERVICE_LINES,
    STAFF_DIRECTORY,
    TOPOLOGY_VERSION,
    buildings_on_line,
    cascade,
    line_for,
    resolve_building,
)
from .database import create_broadcast_alert, get_connection, update_ticket_record
from .demo_scenario import demo_ticket_ids

OPEN = ("New", "Assigned", "In Progress")
CLOSED = ("Resolved", "Closed")
PRIORITY_WEIGHT = {"Critical": 20, "High": 10, "Medium": 5, "Low": 2}
PRIORITY_RANK = {"Low": 0, "Medium": 1, "High": 2, "Critical": 3}
RECENT_WINDOW = timedelta(days=14)
CORRELATION_WINDOW = timedelta(hours=72)
RECURRENCE_WINDOW = timedelta(days=7)
CACHE_TTL = 8.0

_cache: Dict[str, Any] = {"at": 0.0, "snap": None}
_lock = threading.Lock()


# ---------------------------------------------------------------------------
# Storage (additive tables only — existing schema untouched)
# ---------------------------------------------------------------------------

def init_intelligence_tables() -> None:
    conn, engine = get_connection()
    cur = conn.cursor()
    pk = "SERIAL PRIMARY KEY" if engine == "postgresql" else "INTEGER PRIMARY KEY AUTOINCREMENT"
    cur.execute("""
    CREATE TABLE IF NOT EXISTS signal_states (
        signal_key TEXT PRIMARY KEY,
        state TEXT NOT NULL,
        fingerprint TEXT NOT NULL,
        actor TEXT NOT NULL,
        note TEXT,
        updated_at TEXT NOT NULL
    )""")
    cur.execute(f"""
    CREATE TABLE IF NOT EXISTS resolution_verifications (
        id {pk},
        ticket_id TEXT NOT NULL,
        method TEXT NOT NULL,
        actor TEXT NOT NULL,
        note TEXT,
        image TEXT,
        created_at TEXT NOT NULL
    )""")
    cur.execute("""
    CREATE TABLE IF NOT EXISTS reporter_credentials (
        ticket_id TEXT PRIMARY KEY,
        token_hash TEXT NOT NULL,
        created_at TEXT NOT NULL
    )""")
    conn.commit()
    try:
        cur.execute("ALTER TABLE resolution_verifications ADD COLUMN reason TEXT")
        conn.commit()
    except Exception:
        conn.rollback()  # column already exists
    conn.close()


def invalidate() -> None:
    with _lock:
        _cache["snap"] = None


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _parse(ts: Any) -> Optional[datetime]:
    if not ts:
        return None
    try:
        dt = datetime.fromisoformat(str(ts).replace("Z", "+00:00"))
        return dt if dt.tzinfo else dt.replace(tzinfo=timezone.utc)
    except (ValueError, TypeError):
        return None


def _iso(dt: Optional[datetime]) -> Optional[str]:
    return dt.isoformat() if dt else None


def _hours(td: timedelta) -> float:
    return round(td.total_seconds() / 3600, 1)


def _rows(cur) -> List[Dict[str, Any]]:
    return [dict(r) for r in cur.fetchall()]


def _cursor(conn, engine):
    if engine == "postgresql":
        from psycopg2.extras import RealDictCursor
        return conn.cursor(cursor_factory=RealDictCursor)
    return conn.cursor()


# ---------------------------------------------------------------------------
# Snapshot: one consistent read of the operational data (3 queries, no N+1)
# ---------------------------------------------------------------------------

def _load() -> Dict[str, Any]:
    conn, engine = get_connection()
    cur = _cursor(conn, engine)
    cur.execute("""SELECT id, title, location, category, priority, department, status, owner, sla_hours,
                   created_at, resolved_at, summary, CASE WHEN image IS NULL OR image = '' THEN 0 ELSE 1 END AS has_image
                   FROM tickets""")
    tickets = _rows(cur)
    cur.execute("SELECT id, ticket_id, action, actor, created_at, notes FROM activity_logs ORDER BY id ASC")
    logs = _rows(cur)
    cur.execute("SELECT signal_key, state, fingerprint, actor, note, updated_at FROM signal_states")
    states = {r["signal_key"]: r for r in _rows(cur)}
    cur.execute("SELECT id, ticket_id, method, actor, note, reason, created_at, CASE WHEN image IS NULL OR image = '' THEN 0 ELSE 1 END AS has_image FROM resolution_verifications ORDER BY id ASC")
    verifications = _rows(cur)
    cur.execute("SELECT ticket_id FROM reporter_credentials")
    credentialed = {r["ticket_id"] for r in _rows(cur)}
    conn.close()

    logs_by_ticket: Dict[str, List[Dict]] = defaultdict(list)
    for l in logs:
        l["at"] = _parse(l["created_at"])
        logs_by_ticket[l["ticket_id"]].append(l)
    ver_by_ticket: Dict[str, List[Dict]] = defaultdict(list)
    for v in verifications:
        ver_by_ticket[v["ticket_id"]].append(v)

    out = []
    for t in tickets:
        created = _parse(t["created_at"]) or _now()
        tlogs = logs_by_ticket.get(t["id"], [])
        closed_at = _parse(t["resolved_at"])
        if t["status"] in CLOSED and not closed_at:
            # "Closed" clears resolved_at in the existing workflow — recover the time from the audit trail
            for l in reversed(tlogs):
                if l["action"].startswith("Status updated") and ("'Resolved'" in l["action"] or "'Closed'" in l["action"]):
                    closed_at = l["at"]
                    break
        assigned_at = next((l["at"] for l in tlogs if l["action"].startswith("Assigned owner to") and "'Unassigned'" not in l["action"]), None)
        building, mapped = resolve_building(t["location"])
        notes = [l for l in tlogs if l["action"].startswith("Note:")]
        out.append({
            **{k: t[k] for k in ("id", "title", "location", "category", "priority", "department", "status", "owner", "summary")},
            "sla_hours": int(t["sla_hours"] or 24),
            "created": created,
            "due": created + timedelta(hours=int(t["sla_hours"] or 24)),
            "closed_at": closed_at if t["status"] in CLOSED else None,
            "assigned_at": assigned_at,
            "last_activity": max([l["at"] for l in tlogs if l["at"]] or [created]),
            "building": building,
            "mapped": mapped,
            "service": CATEGORY_SERVICE.get(t["category"], "Facilities"),
            "has_image": bool(t["has_image"]),
            "notes": notes,
            "logs": tlogs,
            "verifications": ver_by_ticket.get(t["id"], []),
            "has_credential": t["id"] in credentialed,
        })
    return {"tickets": out, "states": states, "loaded_at": _now()}


def snapshot(force: bool = False) -> Dict[str, Any]:
    with _lock:
        if not force and _cache["snap"] and time.time() - _cache["at"] < CACHE_TTL:
            return _cache["snap"]
    snap = _load()
    with _lock:
        _cache.update(at=time.time(), snap=snap)
    return snap


def _is_open(t: Dict, at: datetime) -> bool:
    if t["created"] > at:
        return False
    if t["status"] in OPEN:
        return True
    return t["closed_at"] is not None and t["closed_at"] > at


def _is_breached(t: Dict, at: datetime) -> bool:
    return _is_open(t, at) and t["due"] < at


def _is_assigned(t: Dict, at: datetime) -> bool:
    if t["owner"] in (None, "", "Unassigned"):
        return False
    return t["assigned_at"] is None or t["assigned_at"] <= at


def _brief(t: Dict, now: Optional[datetime] = None) -> Dict[str, Any]:
    now = now or _now()
    remaining = t["due"] - now
    return {
        "id": t["id"], "title": t["title"], "location": t["location"], "building": t["building"],
        "category": t["category"], "priority": t["priority"], "department": t["department"],
        "status": t["status"], "owner": t["owner"], "created_at": _iso(t["created"]),
        "sla_due_at": _iso(t["due"]),
        "sla_remaining_hours": _hours(remaining) if t["status"] in OPEN else None,
        "is_breached": t["status"] in OPEN and remaining.total_seconds() < 0,
    }


# ---------------------------------------------------------------------------
# Campus Health Index — five dimensions, each with its formula and inputs shown
# ---------------------------------------------------------------------------

DIMENSION_WEIGHTS = {"safety": 0.25, "response": 0.25, "infrastructure": 0.2, "maintenance": 0.15, "network": 0.15}


def compute_health(tickets: List[Dict], at: datetime, breach_overrides: Optional[set] = None,
                   resolved_overrides: Optional[set] = None) -> Dict[str, Any]:
    breach_overrides = breach_overrides or set()
    resolved_overrides = resolved_overrides or set()
    open_t = [t for t in tickets if _is_open(t, at) and t["id"] not in resolved_overrides]
    breached = [t for t in open_t if _is_breached(t, at) or t["id"] in breach_overrides]
    dims: Dict[str, Dict[str, Any]] = {}

    # Response: share of open work inside SLA, blended with on-time resolution over 30 days
    recent_closed = [t for t in tickets if t["closed_at"] and at - timedelta(days=30) <= t["closed_at"] <= at]
    on_time = [t for t in recent_closed if t["closed_at"] <= t["due"]]
    if not open_t and not recent_closed:
        dims["response"] = {"score": None, "detail": "Insufficient data — no open or recently resolved incidents."}
    else:
        within = 1 - (len(breached) / len(open_t)) if open_t else 1.0
        ontime = (len(on_time) / len(recent_closed)) if recent_closed else within
        dims["response"] = {
            "score": round(100 * (0.6 * within + 0.4 * ontime)),
            "detail": f"{len(open_t) - len(breached)}/{len(open_t)} open incidents within SLA; "
                      f"{len(on_time)}/{len(recent_closed)} resolved on time (30 days).",
            "formula": "60% × open-within-SLA ratio + 40% × on-time resolution ratio",
        }

    def load_score(items: List[Dict]) -> int:
        return max(0, 100 - sum(PRIORITY_WEIGHT.get(t["priority"], 5) for t in items))

    safety_items = [t for t in open_t if t["category"] == "Security" or t["priority"] == "Critical"]
    dims["safety"] = {
        "score": load_score(safety_items),
        "detail": f"{len(safety_items)} open safety-relevant incidents (Security category or Critical priority).",
        "formula": "100 − Σ priority weight (Critical 20, High 10, Medium 5, Low 2)",
    }
    infra_items = [t for t in open_t if t["category"] in ("Water", "Electrical", "Infrastructure")]
    dims["infrastructure"] = {
        "score": load_score(infra_items),
        "detail": f"{len(infra_items)} open water / electrical / structural incidents.",
        "formula": "100 − Σ priority weight of open infrastructure incidents",
    }
    net_items = [t for t in open_t if t["category"] == "Network"]
    dims["network"] = {
        "score": load_score(net_items),
        "detail": f"{len(net_items)} open network incidents.",
        "formula": "100 − Σ priority weight of open network incidents",
    }
    if open_t:
        unassigned = [t for t in open_t if not _is_assigned(t, at)]
        stale = [t for t in open_t if (at - min(t["last_activity"], at)) > timedelta(hours=24)]
        dims["maintenance"] = {
            "score": round(100 - 50 * len(unassigned) / len(open_t) - 50 * len(stale) / len(open_t)),
            "detail": f"{len(unassigned)} of {len(open_t)} open incidents unassigned; {len(stale)} with no activity for 24h+.",
            "formula": "100 − 50 × unassigned ratio − 50 × stale (no update 24h) ratio",
        }
    else:
        dims["maintenance"] = {"score": 100, "detail": "No open maintenance backlog.", "formula": "No backlog"}

    scored = {k: v for k, v in dims.items() if v["score"] is not None}
    wsum = sum(DIMENSION_WEIGHTS[k] for k in scored)
    overall = round(sum(v["score"] * DIMENSION_WEIGHTS[k] for k, v in scored.items()) / wsum) if wsum else None
    return {"score": overall, "dimensions": dims, "open": len(open_t), "breached": len(breached),
            "weights": DIMENSION_WEIGHTS}


def health_report(snap: Dict[str, Any]) -> Dict[str, Any]:
    tickets, now = snap["tickets"], snap["loaded_at"]
    if not tickets:
        return {"score": None, "dimensions": {}, "change": None, "message": "No operational data yet."}
    current = compute_health(tickets, now)
    past_at = now - timedelta(hours=24)
    has_history = any(t["created"] <= past_at for t in tickets)
    change = None
    if has_history:
        past = compute_health(tickets, past_at)
        new_24 = [t for t in tickets if past_at < t["created"] <= now]
        newly_breached = [t for t in tickets if past_at < t["due"] <= now and _is_open(t, t["due"])]
        resolved_24 = [t for t in tickets if t["closed_at"] and past_at < t["closed_at"] <= now]
        reasons = []
        hp = Counter(t["priority"] for t in new_24 if t["priority"] in ("Critical", "High"))
        if new_24:
            reasons.append(f"{len(new_24)} new incident{'s' if len(new_24) != 1 else ''} reported"
                           + (f" ({', '.join(f'{v} {k}' for k, v in hp.items())})" if hp else ""))
        if newly_breached:
            reasons.append(f"{len(newly_breached)} incident{'s' if len(newly_breached) != 1 else ''} crossed the SLA deadline")
        if resolved_24:
            reasons.append(f"{len(resolved_24)} incident{'s' if len(resolved_24) != 1 else ''} resolved")
        if current["open"] != past["open"]:
            reasons.append(f"open backlog {'grew' if current['open'] > past['open'] else 'shrank'} from {past['open']} to {current['open']}")
        dim_deltas = {k: (current["dimensions"][k]["score"] - past["dimensions"][k]["score"])
                      if current["dimensions"][k]["score"] is not None and past["dimensions"][k]["score"] is not None else None
                      for k in current["dimensions"]}
        change = {
            "previous": past["score"],
            "delta": (current["score"] - past["score"]) if current["score"] is not None and past["score"] is not None else None,
            "window": "24h",
            "reasons": reasons or ["No material change in the last 24 hours."],
            "dimension_deltas": dim_deltas,
            "method": "Past score reconstructed from ticket creation, SLA and resolution timestamps (current priorities used).",
        }
    return {**current, "change": change,
            "note": None if has_history else "Insufficient history to compute a 24h trend."}


# ---------------------------------------------------------------------------
# Pattern detection, correlation and early warnings
# ---------------------------------------------------------------------------

def _fingerprint(ids: List[str]) -> str:
    return hashlib.sha256(",".join(sorted(ids)).encode()).hexdigest()[:12]


def _least_loaded_staff(tickets: List[Dict], department: str) -> Optional[Dict[str, Any]]:
    load = Counter(t["owner"] for t in tickets if t["status"] in OPEN)
    candidates = [name for name, dept in STAFF_DIRECTORY if dept == department]
    if not candidates:
        return None
    best = min(candidates, key=lambda n: load.get(n, 0))
    return {"name": best, "open_assignments": load.get(best, 0)}


def _history(tickets: List[Dict], building: str, category: str, before: datetime, exclude: set) -> List[Dict]:
    return [t for t in tickets if t["building"] == building and t["category"] == category
            and t["id"] not in exclude and t["created"] < before]


def _recurrence(tickets: List[Dict], group: List[Dict]) -> List[Dict[str, str]]:
    """New reports that arrived within 7 days after a same-building/category incident was closed."""
    hits = []
    for t in group:
        for prev in tickets:
            if (prev["id"] != t["id"] and prev["building"] == t["building"] and prev["category"] == t["category"]
                    and prev["closed_at"] and prev["closed_at"] < t["created"] <= prev["closed_at"] + RECURRENCE_WINDOW):
                verified = any(v["method"] in ("reporter_confirmed", "admin_verified") for v in prev["verifications"])
                hits.append({"ticket": t["id"], "after": prev["id"], "after_verified": verified})
                break
    return hits


def _level(score: int) -> str:
    return "Critical" if score >= 75 else "High" if score >= 55 else "Elevated" if score >= 35 else "Watch"


def _recommendations(sig: Dict, tickets: List[Dict], open_group: List[Dict]) -> List[Dict[str, Any]]:
    recs: List[Dict[str, Any]] = []
    dept = Counter(t["department"] for t in open_group).most_common(1)[0][0] if open_group else None
    unassigned = [t for t in open_group if t["owner"] in (None, "", "Unassigned")]
    if unassigned and dept:
        staff = _least_loaded_staff(tickets, dept)
        if staff:
            recs.append({
                "title": f"Assign {staff['name']} to {len(unassigned)} unassigned incident{'s' if len(unassigned) != 1 else ''}",
                "why": f"Least-loaded {dept} staff member ({staff['open_assignments']} open assignments).",
                "actions": [{"type": "assign", "ticket_id": t["id"], "owner": staff["name"]} for t in unassigned],
            })
    urgent = [t for t in open_group if (t["due"] - _now()) < timedelta(hours=max(2, t["sla_hours"] * 0.25))
              and PRIORITY_RANK.get(t["priority"], 1) < PRIORITY_RANK["High"]]
    if urgent:
        recs.append({
            "title": f"Escalate {len(urgent)} incident{'s' if len(urgent) != 1 else ''} near or past SLA to High",
            "why": "Less than 25% of the SLA window remains (or already breached) at Medium/Low priority.",
            "actions": [{"type": "escalate", "ticket_id": t["id"], "priority": "High"} for t in urgent],
        })
    if sig.get("line"):
        recs.append({
            "title": f"Inspect shared {sig['service'].lower()} infrastructure: {sig['line']}",
            "why": "Reports from multiple buildings on the same configured supply line suggest a possible common cause.",
            "actions": [{"type": "add_note", "ticket_id": t["id"],
                         "note": f"Future Engine: possible common cause on {sig['line']} — inspect shared line before individual repairs."}
                        for t in open_group],
        })
    elif len(open_group) >= 2:
        recs.append({
            "title": f"Inspect common {sig['service'].lower()} infrastructure in {sig['building']}",
            "why": f"{len(open_group)} open reports in the same building and category — treat as one investigation.",
            "actions": [{"type": "add_note", "ticket_id": t["id"],
                         "note": f"Future Engine: linked to pattern '{sig['title']}' — investigate as possible common cause."}
                        for t in open_group],
        })
    if sig["level"] in ("High", "Critical") and sig.get("building_type") in ("Residential", "Dining", "Academic"):
        recs.append({
            "title": f"Post a campus advisory for {sig['where']}",
            "why": f"Keeps occupants informed while {sig['service'].lower()} issues are investigated.",
            "actions": [{"type": "broadcast", "title": f"{sig['service']} issue under investigation — {sig['where']}",
                         "message": f"Operations is investigating {len(open_group)} related {sig['service'].lower()} reports. Please report new symptoms via KAIROS.",
                         "level": "warning", "sector": sig["where"][:100]}],
        })
    recs.append({"title": "Monitor for new related reports", "why": "KAIROS re-evaluates this signal automatically as reports arrive.", "actions": []})
    return recs


def _build_signal(kind: str, key: str, title: str, where: str, service: str, group: List[Dict],
                  tickets: List[Dict], now: datetime, building: Optional[str] = None, line: Optional[str] = None) -> Dict[str, Any]:
    open_group = [t for t in group if t["status"] in OPEN]
    ids = [t["id"] for t in group]
    breached = [t for t in open_group if t["due"] < now]
    near = [t for t in open_group if timedelta(0) <= t["due"] - now < timedelta(hours=max(2, t["sla_hours"] * 0.25))]
    crit = [t for t in open_group if t["priority"] == "Critical"]
    high = [t for t in open_group if t["priority"] == "High"]
    unassigned = [t for t in open_group if t["owner"] in (None, "", "Unassigned")]
    first = min(t["created"] for t in group)
    hist: List[Dict] = []
    for b in {t["building"] for t in group}:
        hist += _history(tickets, b, group[0]["category"], first, set(ids))
    recur = _recurrence(tickets, group)
    dept = Counter(t["department"] for t in group).most_common(1)[0][0]
    dept_backlog = sum(1 for t in tickets if t["status"] in OPEN and t["department"] == dept)

    indicators = [
        {"key": "volume", "label": f"{len(group)} related reports within {_hours(max(t['created'] for t in group) - first) or 0}h",
         "points": min(len(group), 5) * 6, "present": len(group) >= 2},
        {"key": "severity", "label": f"{len(crit)} Critical / {len(high)} High open", "points": min(30, len(crit) * 12 + len(high) * 6), "present": bool(crit or high)},
        {"key": "sla", "label": f"{len(breached)} past SLA, {len(near)} approaching", "points": min(20, len(breached) * 8 + len(near) * 4), "present": bool(breached or near)},
        {"key": "recurrence", "label": f"Possible recurrence: {len(recur)} report{'s' if len(recur) != 1 else ''} within 7 days of a prior fix"
                                        + (f" ({sum(1 for r in recur if r['after_verified'])} after a verified fix)" if any(r['after_verified'] for r in recur) else ""),
         "points": 12 if recur else 0, "present": bool(recur)},
        {"key": "history", "label": f"{len(hist)} earlier incident{'s' if len(hist) != 1 else ''} of this type here", "points": 10 if len(hist) >= 2 else 5 if hist else 0, "present": bool(hist)},
        {"key": "capacity", "label": f"{dept} backlog: {dept_backlog} open", "points": 5 if dept_backlog >= 5 else 0, "present": dept_backlog >= 5},
        {"key": "ownership", "label": f"{len(unassigned)} unassigned", "points": 5 if unassigned else 0, "present": bool(unassigned)},
    ]
    if line:
        indicators.insert(1, {"key": "shared_line", "label": f"{len({t['building'] for t in group})} buildings share {line}",
                              "points": 10, "present": True})
    score = min(95, sum(i["points"] for i in indicators))
    present = sum(1 for i in indicators if i["present"])
    btype = BUILDINGS.get(building or "", {}).get("type")
    notes = []
    if not all(t["mapped"] for t in group):
        notes.append("Some locations are not in the campus topology; building-level correlation is limited.")
    if len({t["id"] for t in hist}) == 0:
        notes.append("Insufficient historical data for this building and category — risk is based on current reports only.")

    newest = max(group, key=lambda t: t["created"])
    sig = {
        "id": key, "kind": kind, "title": title, "where": where, "building": building, "building_type": btype,
        "line": line, "service": service, "category": group[0]["category"],
        "score": score, "level": _level(score),
        "evidence_strength": {"indicators_present": present, "indicators_total": len(indicators),
                              "label": "Strong" if present >= 5 else "Moderate" if present >= 3 else "Limited"},
        "indicators": indicators,
        "ticket_ids": ids, "open_ticket_ids": [t["id"] for t in open_group],
        "tickets": [_brief(t, now) for t in sorted(group, key=lambda t: t["created"], reverse=True)],
        "history": [{"id": h["id"], "title": h["title"], "created_at": _iso(h["created"]), "status": h["status"]} for h in hist[:6]],
        "recurrence": recur,
        "first_seen": _iso(first), "last_seen": _iso(newest["created"]),
        "newest": _brief(newest, now),
        "notes": notes,
        "fingerprint": _fingerprint(ids),
    }
    if btype:
        impact_scope = BUILDING_IMPACT.get(btype, "occupants of the affected area")
    else:
        members = sorted({t["building"] for t in group})
        kinds = sorted({BUILDINGS[b]["type"].lower() for b in members if b in BUILDINGS})
        impact_scope = f"occupants of {', '.join(members)}" + (f" ({', '.join(kinds)} buildings)" if kinds else "")
    sig["potential_impact"] = {
        "summary": f"If unresolved, {service.lower()} disruption in {where} would affect {impact_scope}.",
        "open_incidents": len(open_group), "sla_breached": len(breached), "sla_at_risk": len(near),
        "population": None, "population_note": "Occupancy data not configured — affected population is not estimated.",
    }
    sig["recommendations"] = _recommendations(sig, tickets, open_group)
    sig["analysis_stages"] = [
        {"stage": "Signal detected", "detail": f"{newest['id']}: {newest['title']}"},
        {"stage": "Related incidents found", "detail": f"{len(group)} reports linked by {'shared ' + line if line else 'building and category'}"},
        {"stage": "Emerging pattern", "detail": title},
        {"stage": "Risk assessed", "detail": f"{sig['level']} · score {score}/100 · {present} of {len(indicators)} indicators present"},
        {"stage": "Potential impact", "detail": sig["potential_impact"]["summary"]},
        {"stage": "Intervention recommended", "detail": sig["recommendations"][0]["title"]},
    ]
    return sig


def detect_signals(snap: Dict[str, Any]) -> List[Dict[str, Any]]:
    tickets, now = snap["tickets"], snap["loaded_at"]
    # Live members: open incidents from the recent window, or anything reported in the last 72h.
    # Older closed incidents are not members — they feed the history / recurrence evidence instead.
    recent = [t for t in tickets if now - t["created"] <= RECENT_WINDOW
              and (t["status"] in OPEN or now - t["created"] <= CORRELATION_WINDOW)]
    signals: List[Dict[str, Any]] = []

    # 1. Same building + same category clusters
    groups: Dict[tuple, List[Dict]] = defaultdict(list)
    for t in recent:
        groups[(t["building"], t["category"])].append(t)
    for (building, category), group in groups.items():
        if len(group) >= 2 and any(t["status"] in OPEN for t in group):
            service = CATEGORY_SERVICE.get(category, "Facilities")
            signals.append(_build_signal(
                "cluster", f"cluster:{building}:{category}", f"{category} incidents clustering in {building}",
                building, service, group, tickets, now, building=building))

    # 2. Cross-building correlation on shared supply lines (possible common cause)
    for service, lines in SERVICE_LINES.items():
        cats = [c for c, s in CATEGORY_SERVICE.items() if s == service]
        for line, members in lines.items():
            group = [t for t in recent if t["category"] in cats and t["building"] in members
                     and now - t["created"] <= CORRELATION_WINDOW]
            if len({t["building"] for t in group}) >= 2 and any(t["status"] in OPEN for t in group):
                signals.append(_build_signal(
                    "shared_line", f"line:{service}:{line}", f"Possible common {service.lower()} cause on {line}",
                    line, service, group, tickets, now, line=line))

    # 3. Multi-system stress in a single building
    by_building: Dict[str, List[Dict]] = defaultdict(list)
    for t in tickets:
        if t["status"] in OPEN:
            by_building[t["building"]].append(t)
    for building, group in by_building.items():
        if len(group) >= 3 and len({t["category"] for t in group}) >= 2:
            sig = _build_signal("building_stress", f"stress:{building}", f"Multiple systems under stress in {building}",
                                building, "Facilities", group, tickets, now, building=building)
            sig["category"] = "Multiple"
            signals.append(sig)

    signals.sort(key=lambda s: s["score"], reverse=True)
    return signals


def sla_risks(snap: Dict[str, Any]) -> Dict[str, List[Dict]]:
    now = snap["loaded_at"]
    open_t = [t for t in snap["tickets"] if t["status"] in OPEN]
    breached = sorted([t for t in open_t if t["due"] < now], key=lambda t: t["due"])
    approaching = sorted([t for t in open_t if timedelta(0) <= t["due"] - now < timedelta(hours=max(2, t["sla_hours"] * 0.25))],
                         key=lambda t: t["due"])
    return {"breached": [_brief(t, now) for t in breached], "approaching": [_brief(t, now) for t in approaching]}


def _state_for(snap: Dict, key: str, fingerprint: str) -> Dict[str, Any]:
    st = snap["states"].get(key)
    if not st:
        return {"state": "active"}
    if st["fingerprint"] != fingerprint and st["state"] in ("dismissed", "acknowledged", "actioned"):
        return {"state": "active", "resurfaced": True, "previous": st["state"],
                "reason": "New evidence since it was " + st["state"] + "."}
    return {"state": st["state"], "actor": st["actor"], "updated_at": st["updated_at"], "note": st["note"]}


def early_warnings(snap: Dict[str, Any], signals: Optional[List[Dict]] = None) -> List[Dict[str, Any]]:
    signals = signals if signals is not None else detect_signals(snap)
    now = snap["loaded_at"]
    warnings = []
    for s in signals:
        warnings.append({
            "id": s["id"], "kind": s["kind"], "level": s["level"], "score": s["score"],
            "what": s["title"], "where": s["where"],
            "why": "; ".join(i["label"] for i in s["indicators"] if i["present"]),
            "evidence": s["indicators"], "ticket_ids": s["ticket_ids"],
            "potential_impact": s["potential_impact"]["summary"],
            "recommended_action": s["recommendations"][0]["title"],
            "recommendations": s["recommendations"],
            "fingerprint": s["fingerprint"],
            **_state_for(snap, s["id"], s["fingerprint"]),
        })
    risks = sla_risks(snap)
    if risks["approaching"]:
        ids = [t["id"] for t in risks["approaching"]]
        fp = _fingerprint(ids)
        tickets_by_id = {t["id"]: t for t in snap["tickets"]}
        sig = {"title": "SLA deadlines approaching", "where": "Campus-wide", "service": "Response", "building": None}
        group = [tickets_by_id[i] for i in ids]
        warnings.append({
            "id": "sla:approaching", "kind": "sla", "level": "High" if len(ids) >= 3 else "Elevated", "score": min(100, 20 * len(ids)),
            "what": f"{len(ids)} incident{'s' if len(ids) != 1 else ''} approaching SLA breach",
            "where": ", ".join(sorted({t["building"] for t in group}))[:120],
            "why": "Less than 25% of the SLA window remains: " + ", ".join(f"{t['id']} ({t['sla_remaining_hours']}h)" for t in risks["approaching"][:5]),
            "evidence": [{"label": f"{t['id']} · {t['priority']} · {t['sla_remaining_hours']}h left · owner {t['owner']}", "present": True} for t in risks["approaching"]],
            "ticket_ids": ids,
            "potential_impact": f"{len(ids)} additional SLA breach{'es' if len(ids) != 1 else ''} if not actioned.",
            "recommended_action": "Assign and escalate before the deadline",
            "recommendations": _recommendations({**sig, "level": "High", "line": None, "building_type": None}, snap["tickets"], group),
            "fingerprint": fp, **_state_for(snap, "sla:approaching", fp),
        })
    for t in snap["tickets"]:
        v = verification_for(t, snap["tickets"], now)
        if v["state"] not in ("disputed_returned", "disputed"):
            continue
        d = v["last_dispute"]
        fp = _fingerprint([t["id"], str(d["verification_id"])])
        key = f"dispute:{t['id']}"
        recs = []
        if t["owner"] in (None, "", "Unassigned"):
            staff = _least_loaded_staff(snap["tickets"], t["department"])
            if staff:
                recs.append({"title": f"Assign {staff['name']} to re-inspect {t['id']}", "why": "Disputed resolution has no owner.",
                             "actions": [{"type": "assign", "ticket_id": t["id"], "owner": staff["name"]}]})
        recs.append({"title": f"Log re-inspection directive on {t['id']}", "why": f"Reporter says: {d['reason_label']}.",
                     "actions": [{"type": "add_note", "ticket_id": t["id"], "note": f"Re-inspection required: reporter disputed the fix ({d['reason_label']})."}]})
        warnings.append({
            "id": key, "kind": "dispute", "level": "High" if t["priority"] in ("Critical", "High") else "Elevated",
            "score": 55 if t["priority"] in ("Critical", "High") else 40,
            "what": f"Reverification required: reporter disputed {t['id']}", "where": t["building"],
            "why": f"Marked resolved {v['resolved_at'][:16].replace('T', ' ') if v['resolved_at'] else ''} UTC; reporter responded “{d['reason_label']}”"
                   + (" with a photo" if d["has_image"] else "") + f". Ticket is now {t['status']}.",
            "evidence": [{"label": e["label"], "present": True} for e in v["evidence"]],
            "ticket_ids": [t["id"]], "ticket_title": t["title"],
            "potential_impact": "The reported problem may still be affecting people despite being marked resolved.",
            "recommended_action": "Review the incident and re-inspect",
            "recommendations": recs, "dispute": {k: d[k] for k in ("reason_label", "at", "has_image")},
            "fingerprint": fp, **_state_for(snap, key, fp),
        })
    order = {"Critical": 0, "High": 1, "Elevated": 2, "Watch": 3}
    warnings.sort(key=lambda w: (w["state"] != "active", order.get(w["level"], 4), -w["score"]))
    return warnings


def set_signal_state(key: str, state: str, fingerprint: str, actor: str, note: Optional[str]) -> None:
    conn, engine = get_connection()
    cur = conn.cursor()
    ph = "%s" if engine == "postgresql" else "?"
    now = _now().isoformat()
    cur.execute(f"DELETE FROM signal_states WHERE signal_key = {ph}", (key,))
    cur.execute(f"INSERT INTO signal_states (signal_key, state, fingerprint, actor, note, updated_at) VALUES ({ph},{ph},{ph},{ph},{ph},{ph})",
                (key, state, fingerprint, actor, note, now))
    conn.commit()
    conn.close()
    invalidate()


# ---------------------------------------------------------------------------
# Incident relationship graph
# ---------------------------------------------------------------------------

def incident_graph(snap: Dict[str, Any], signal_id: Optional[str] = None, signals: Optional[List[Dict]] = None) -> Dict[str, Any]:
    signals = signals if signals is not None else detect_signals(snap)
    chosen = [s for s in signals if s["id"] == signal_id] if signal_id else signals[:4]
    nodes: Dict[str, Dict] = {}
    edges: List[Dict] = []
    by_id = {t["id"]: t for t in snap["tickets"]}

    def node(nid, ntype, label, **extra):
        nodes.setdefault(nid, {"id": nid, "type": ntype, "label": label, **extra})

    for s in chosen:
        sid = f"pattern:{s['id']}"
        node(sid, "pattern", s["title"], level=s["level"], score=s["score"])
        for tid in s["ticket_ids"]:
            t = by_id.get(tid)
            if not t:
                continue
            node(f"ticket:{tid}", "incident", tid, title=t["title"], priority=t["priority"], status=t["status"])
            node(f"building:{t['building']}", "building", t["building"])
            node(f"service:{t['service']}", "service", t["service"])
            edges.append({"from": f"ticket:{tid}", "to": f"building:{t['building']}", "rel": "located in"})
            edges.append({"from": f"ticket:{tid}", "to": f"service:{t['service']}", "rel": "affects"})
            edges.append({"from": f"ticket:{tid}", "to": sid, "rel": "signal of"})
            line = line_for(t["building"], t["service"])
            if line:
                node(f"line:{line}", "line", line)
                edges.append({"from": f"building:{t['building']}", "to": f"line:{line}", "rel": "supplied by"})
                edges.append({"from": f"line:{line}", "to": f"service:{t['service']}", "rel": "carries"})
            else:
                edges.append({"from": f"building:{t['building']}", "to": f"service:{t['service']}", "rel": "uses"})
            edges.append({"from": f"service:{t['service']}", "to": sid, "rel": "pattern in"})
        edges.append({"from": sid, "to": f"cause:{s['id']}", "rel": "possible common cause"})
        node(f"cause:{s['id']}", "cause", f"Possible common cause: {s['line'] or s['building'] or s['where']}")
    unique = list({(e["from"], e["to"]): e for e in edges}.values())
    return {"nodes": list(nodes.values()), "edges": unique,
            "note": "Relationships come from ticket data (location, category, timing) and the configured campus topology."}


# ---------------------------------------------------------------------------
# Scenario simulation (What-If)
# ---------------------------------------------------------------------------

def _scenario_outcome(tickets: List[Dict], affected: List[Dict], now: datetime, horizon: timedelta,
                      extra_delay: timedelta = timedelta(0)) -> Dict[str, Any]:
    """Project SLA breaches and health at now+horizon if nothing is done vs. if affected work is actioned in time."""
    end = now + horizon
    would_breach = [t for t in affected if t["status"] in OPEN and t["due"] <= end + extra_delay and t["due"] > now]
    already = [t for t in affected if t["status"] in OPEN and t["due"] <= now]
    base = compute_health(tickets, now)
    no_action = compute_health(tickets, now, breach_overrides={t["id"] for t in would_breach + already})
    with_action = compute_health(tickets, now, resolved_overrides={t["id"] for t in would_breach})
    return {"would_breach": would_breach, "already_breached": already,
            "health_now": base["score"], "health_no_action": no_action["score"], "health_with_action": with_action["score"]}


def simulate(snap: Dict[str, Any], scenario: Dict[str, Any]) -> Dict[str, Any]:
    tickets, now = snap["tickets"], snap["loaded_at"]
    stype = scenario.get("type")
    hours = max(1, min(int(scenario.get("hours") or 24), 168))
    horizon = timedelta(hours=hours)
    label = "Scenario estimate based on available operational relationships"
    assumptions = [f"Campus topology: {TOPOLOGY_VERSION}.",
                   "'With preventive action' assumes the at-risk incidents are assigned and closed within their SLA.",
                   "Affected population is not estimated (occupancy not configured)."]

    if stype == "service_outage":
        building, service = scenario.get("building"), scenario.get("service")
        if building not in BUILDINGS or service not in SERVICE_LINES:
            raise ValueError("Choose a configured building and one of: " + ", ".join(SERVICE_LINES))
        scope = scenario.get("scope", "building")
        line = line_for(building, service)
        affected_b = buildings_on_line(service, line) if scope == "line" and line else [building]
        services = [service] + cascade(service)
        cats = {c for c, s in CATEGORY_SERVICE.items() if s in services} | {"Infrastructure"}
        affected = [t for t in tickets if t["building"] in affected_b and t["status"] in OPEN]
        related = [t for t in affected if t["category"] in cats]
        out = _scenario_outcome(tickets, related, now, horizon)
        out["blocked"] = [t["id"] for t in related]
        title = f"{service} loss at {building if scope == 'building' else line} for {hours}h"
        current = f"{len(affected)} open incidents in the affected area ({len(related)} related to {service.lower()} or dependent services)."
        impacts = [f"{b} ({BUILDINGS[b]['type']}): {BUILDING_IMPACT[BUILDINGS[b]['type']]}" for b in affected_b]
        dependencies = [f"{service} → {d}" for d in cascade(service)] + ([f"{building} is on {line}"] if line else [])
        response = [
            f"Notify occupants of {', '.join(affected_b)} via campus broadcast",
            f"Dispatch {'Electrical Maintenance' if service == 'Power' else 'Facilities' if service == 'Water' else 'IT Infrastructure'} to the affected {'line' if scope == 'line' else 'building'}",
            f"Prioritise {len(out['would_breach'])} incident(s) whose SLA falls inside the outage window" if out["would_breach"] else "No open SLA deadlines fall inside the outage window",
        ]
        if "Lifts" in services:
            response.append("Check lifts for trapped occupants and enable manual override")
        if "Pumped Water" in services:
            response.append("Arrange temporary water supply for upper floors (pumped supply stops)")
    elif stype == "delay_ticket":
        tid = (scenario.get("ticket_id") or "").upper()
        t = next((x for x in tickets if x["id"] == tid), None)
        if not t:
            raise ValueError(f"Ticket {tid} not found.")
        if t["status"] not in OPEN:
            raise ValueError(f"{tid} is already {t['status']} — nothing to delay.")
        same = [x for x in tickets if x["building"] == t["building"] and x["category"] == t["category"] and x["status"] in OPEN]
        remaining = t["due"] - now
        breaches = remaining < horizon
        out = _scenario_outcome(tickets, [t], now, horizon)
        if breaches and t not in out["would_breach"] and t not in out["already_breached"]:
            out["would_breach"].append(t)
        affected_b = [t["building"]]
        services = [t["service"]] + cascade(t["service"])
        title = f"Delay {tid} by {hours}h"
        current = f"{tid} ({t['priority']}, {t['status']}) has {_hours(remaining)}h of SLA remaining; {len(same) - 1} other open {t['category'].lower()} report(s) in {t['building']}."
        impacts = [f"{tid} {'would breach its SLA' if breaches else 'would still be inside its SLA'} after a {hours}h delay"]
        if len(same) > 1:
            impacts.append(f"{len(same) - 1} related open report(s) in the same building remain exposed to the same cause")
        dependencies = [f"{t['service']} → {d}" for d in cascade(t["service"])]
        response = ([f"Do not delay — assign now; {_hours(remaining)}h of SLA remain"] if breaches else
                    [f"Delay is possible within SLA ({_hours(remaining - horizon)}h buffer would remain)"])
    elif stype == "ignore_signal":
        signals = detect_signals(snap)
        sig = next((s for s in signals if s["id"] == scenario.get("signal_id")), None)
        if not sig:
            raise ValueError("That risk signal is no longer active.")
        group = [t for t in tickets if t["id"] in sig["open_ticket_ids"]]
        out = _scenario_outcome(tickets, group, now, horizon)
        affected_b = sorted({t["building"] for t in group})
        services = [sig["service"]] + cascade(sig["service"]) if sig["service"] in SERVICE_LINES else [sig["service"]]
        title = f"Do nothing about “{sig['title']}” for {hours}h"
        current = f"{len(group)} open linked incident(s); risk {sig['level']} ({sig['score']}/100)."
        impacts = [sig["potential_impact"]["summary"]]
        if sig["recurrence"]:
            impacts.append(f"{len(sig['recurrence'])} report(s) already recurred within 7 days of a fix — repeat reports are likely to continue")
        dependencies = [f"{sig['service']} → {d}" for d in cascade(sig["service"])]
        if sig.get("line"):
            dependencies.append(f"Buildings on {sig['line']}: {', '.join(buildings_on_line(sig['service'], sig['line']))}")
        response = [r["title"] for r in sig["recommendations"] if r["actions"]]
    else:
        raise ValueError("Unknown scenario type. Use service_outage, delay_ticket or ignore_signal.")

    history = [t for t in tickets if t["building"] in affected_b and t["closed_at"]]
    return {
        "title": title, "label": label, "horizon_hours": hours, "generated_at": now.isoformat(),
        "current_state": current,
        "affected_buildings": affected_b, "affected_services": services,
        "potential_impact": impacts, "dependencies": dependencies, "recommended_response": response,
        "no_action": {
            "sla_breaches": len(out["would_breach"]) + len(out["already_breached"]),
            "new_breaches": [x["id"] for x in out["would_breach"]],
            "health": out["health_no_action"],
            "summary": f"{len(out['would_breach'])} additional SLA breach(es) within {hours}h; campus health {out['health_now']} → {out['health_no_action']}."
                       + (f" {len(out['blocked'])} open related incident(s) cannot be worked during the disruption." if out.get("blocked") else ""),
            "blocked_incidents": out.get("blocked", []),
        },
        "with_action": {
            "sla_breaches": len(out["already_breached"]),
            "breaches_avoided": len(out["would_breach"]),
            "health": out["health_with_action"],
            "summary": f"{len(out['would_breach'])} breach(es) avoided if actioned now; campus health {out['health_now']} → {out['health_with_action']}.",
        },
        "health_now": out["health_now"],
        "historical_precedents": len(history),
        "assumptions": assumptions,
    }


# ---------------------------------------------------------------------------
# Campus memory & proof of resolution
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Resolution reverification — the reporter closes the loop, not the admin's "Done".
# Derived from real state only: ticket status, audit log transitions and resolution_verifications.
# ---------------------------------------------------------------------------

DISPUTE_REASONS = {
    "unresolved": "Completely unresolved",
    "partial": "Partially resolved",
    "returned": "Problem returned",
    "different": "Different issue remains",
}
MAX_REPORTER_RESPONSES = 5  # per ticket, across all resolution cycles


def verification_policy(t: Dict) -> Dict[str, str]:
    """Extension point for configurable policies. Today: one rule set derived from priority."""
    if t["priority"] == "Critical":
        return {"level": "required", "label": "Reporter verification required (Critical incident)"}
    return {"level": "recommended", "label": "Reporter verification recommended"}


def issue_reporter_token(ticket_id: str) -> str:
    """Secret handed to the submitter once; only its SHA-256 is stored."""
    token = secrets.token_urlsafe(24)
    conn, engine = get_connection()
    cur = conn.cursor()
    ph = "%s" if engine == "postgresql" else "?"
    cur.execute(f"DELETE FROM reporter_credentials WHERE ticket_id = {ph}", (ticket_id,))
    cur.execute(f"INSERT INTO reporter_credentials (ticket_id, token_hash, created_at) VALUES ({ph},{ph},{ph})",
                (ticket_id, hashlib.sha256(token.encode()).hexdigest(), _now().isoformat()))
    conn.commit()
    conn.close()
    return token


def check_reporter_token(ticket_id: str, token: Optional[str]) -> bool:
    if not token or len(token) > 100:
        return False
    conn, engine = get_connection()
    cur = conn.cursor()
    ph = "%s" if engine == "postgresql" else "?"
    cur.execute(f"SELECT token_hash FROM reporter_credentials WHERE ticket_id = {ph}", (ticket_id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return False
    stored = row["token_hash"] if isinstance(row, dict) else row[0]
    return hmac.compare_digest(stored, hashlib.sha256(token.encode()).hexdigest())


def _status_events(t: Dict) -> List[Dict[str, Any]]:
    out = []
    for l in t["logs"]:
        if l["action"].startswith("Status updated from"):
            try:
                frm = l["action"].split("'")[1]
                to = l["action"].split("'")[3]
            except IndexError:
                continue
            out.append({"from": frm, "to": to, "at": l["at"], "actor": l["actor"]})
    return out


def _resolution_times(t: Dict) -> List[datetime]:
    """Moments the ticket moved from open work into Resolved/Closed (each starts a verification cycle)."""
    times = [e["at"] for e in _status_events(t) if e["to"] in CLOSED and e["from"] not in CLOSED and e["at"]]
    if not times and t["closed_at"]:
        times = [t["closed_at"]]
    return times


def _public_actor(actor: str) -> str:
    if actor.startswith("Admin") or "Future Engine" in actor:
        return "Operations team"
    if actor in ("KAIROS Triage", "KAIROS", "KAIROS Reverification"):
        return "KAIROS"
    return actor


def _lifecycle(t: Dict, include_private: bool) -> List[Dict[str, Any]]:
    events: List[Dict[str, Any]] = []
    seen_assign = False
    for l in t["logs"]:
        a, at = l["action"], _iso(l["at"])
        actor = l["actor"] if include_private else _public_actor(l["actor"])
        if a.startswith("Complaint submitted"):
            events.append({"stage": "Report created", "kind": "report", "at": at, "actor": actor})
        elif "classified as" in a:
            events.append({"stage": "AI triaged", "kind": "triage", "at": at, "actor": actor, "detail": a.replace("KAIROS classified as ", "")})
        elif a.startswith("Assigned owner to") and "'Unassigned'" not in a and not seen_assign:
            seen_assign = True
            events.append({"stage": "Assigned", "kind": "assign", "at": at, "actor": actor, "detail": a.split("'")[1] if include_private or True else None})
        elif a.startswith("Status updated from"):
            parts = a.split("'")
            frm, to = (parts[1], parts[3]) if len(parts) > 3 else ("", "")
            if to == "In Progress" and frm not in CLOSED:
                events.append({"stage": "Work started", "kind": "work", "at": at, "actor": actor})
            elif to in CLOSED and frm not in CLOSED:
                events.append({"stage": "Marked resolved", "kind": "resolved", "at": at, "actor": actor})
            elif frm in CLOSED and to not in CLOSED:
                events.append({"stage": "Reopened for review", "kind": "reopened", "at": at, "actor": actor})
        elif a.startswith("Reporter reverification requested"):
            events.append({"stage": "Reverification requested", "kind": "requested", "at": at, "actor": "KAIROS"})
    for v in t["verifications"]:
        label = {"reporter_confirmed": "Reporter verified", "reporter_disputed": "Reporter disputed",
                 "admin_verified": "Administrator verified"}.get(v["method"], v["method"])
        ev = {"stage": label, "kind": v["method"], "at": v["created_at"],
              "actor": "Reporter" if v["method"].startswith("reporter") else ("Operations team" if not include_private else v["actor"])}
        if v["method"] == "reporter_disputed":
            ev["detail"] = DISPUTE_REASONS.get(v.get("reason") or "", "Problem still exists")
        events.append(ev)
    events.sort(key=lambda e: e["at"] or "")
    return events


def verification_for(t: Dict, tickets: List[Dict], now: datetime, include_private: bool = False,
                     has_credential: Optional[bool] = None, admin_view: bool = False) -> Dict[str, Any]:
    has_credential = t.get("has_credential", False) if has_credential is None else has_credential
    res_times = _resolution_times(t)
    last_res = res_times[-1] if res_times else None
    cycle = [v for v in t["verifications"] if last_res and (_parse(v["created_at"]) or now) >= last_res]
    reporter_cycle = [v for v in cycle if v["method"].startswith("reporter")]
    disputes = [v for v in t["verifications"] if v["method"] == "reporter_disputed"]
    reopen_count = sum(1 for e in _status_events(t) if e["from"] in CLOSED and e["to"] not in CLOSED)
    last_dispute = disputes[-1] if disputes else None
    is_closed = t["status"] in CLOSED

    if not is_closed:
        if last_dispute and last_res and (_parse(last_dispute["created_at"]) or now) >= last_res:
            status, state = "Disputed", "disputed_returned"
        else:
            status, state = "Open", "open"
    elif any(v["method"] == "reporter_confirmed" for v in reporter_cycle):
        status, state = "Verified", "verified_reporter"
    elif any(v["method"] == "reporter_disputed" for v in reporter_cycle):
        status, state = "Disputed", "disputed"
    elif any(v["method"] == "admin_verified" for v in cycle):
        status, state = "Verified", "verified_admin"
    elif has_credential:
        status, state = "Awaiting reverification", "awaiting_reporter"
    else:
        status, state = "Resolved — awaiting verification", "awaiting_admin"

    evidence = []
    if last_res:
        evidence.append({"type": "timestamp", "label": f"Marked resolved {last_res.strftime('%Y-%m-%d %H:%M')} UTC"})
    if t["owner"] not in (None, "", "Unassigned"):
        evidence.append({"type": "assignment", "label": f"Handled by {t['owner']} ({t['department']})"})
    tech_notes = [n for n in t["notes"] if t["assigned_at"] is None or (n["at"] and n["at"] >= t["assigned_at"])]
    if tech_notes:
        evidence.append({"type": "technician_update", "label": f"Technician/admin update: “{tech_notes[-1]['action'][6:][:140]}”"})
    if t["has_image"]:
        evidence.append({"type": "intake_photo", "label": "Photo on file from the original report (intake evidence, not proof of fix)"})
    evidence.append({"type": "location", "label": f"Location: {t['location']}"})

    # Possible recurrence: a similar report after this resolution. Evidence only — not proof the fix failed.
    recurrence = []
    if last_res:
        verified_at = next((_parse(v["created_at"]) for v in cycle if v["method"] in ("reporter_confirmed", "admin_verified")), None)
        anchor = verified_at or last_res
        follow = [x for x in tickets if x["id"] != t["id"] and x["building"] == t["building"] and x["category"] == t["category"]
                  and anchor < x["created"] <= anchor + RECURRENCE_WINDOW]
        for f in follow:
            days = max(0.1, (f["created"] - anchor).total_seconds() / 86400)
            recurrence.append({"ticket_id": f["id"], "title": f["title"], "reported_at": _iso(f["created"]),
                               "after": "verification" if verified_at else "resolution",
                               "label": f"Possible recurrence detected: {f['id']} ({t['category'].lower()}, {t['building']}) reported "
                                        f"{days:.1f} day(s) after {'verification' if verified_at else 'resolution'}"})
        if recurrence:
            evidence += [{"type": "possible_recurrence", "label": r["label"], "negative": True} for r in recurrence]
        elif (now - anchor) >= timedelta(hours=24):
            evidence.append({"type": "no_recurrence", "label": f"No similar report in the {min(7, (now - anchor).days or 1)} day(s) since {'verification' if verified_at else 'resolution'}"})

    for v in cycle:
        label = {"admin_verified": "Administrator verification (does not replace reporter confirmation)",
                 "reporter_confirmed": "Reporter confirmed the fix",
                 "reporter_disputed": f"Reporter disputed: {DISPUTE_REASONS.get(v.get('reason') or '', 'problem still exists')}"}.get(v["method"], v["method"])
        if include_private and v.get("note"):
            label += f" — “{v['note']}”"
        if v.get("has_image"):
            label += " (photo attached)"
        evidence.append({"type": v["method"], "label": label, "at": v["created_at"], "negative": v["method"] == "reporter_disputed"})

    decisive = next((v for v in reversed(reporter_cycle)), None) or next((v for v in reversed(cycle)), None)
    dispute_info = None
    if last_dispute:
        dispute_info = {"reason": last_dispute.get("reason"), "reason_label": DISPUTE_REASONS.get(last_dispute.get("reason") or "", "Problem still exists"),
                        "at": last_dispute["created_at"], "has_image": bool(last_dispute.get("has_image")), "verification_id": last_dispute["id"],
                        "note": last_dispute.get("note") if include_private else None}

    lifecycle = _lifecycle(t, admin_view)  # staff identities only for administrators
    if state == "awaiting_reporter":
        lifecycle.append({"stage": "Awaiting reverification", "kind": "pending", "at": None, "actor": "Reporter"})

    return {
        "status": status, "state": state,
        "reporter_can_respond": is_closed and has_credential and not reporter_cycle,
        "evidence": evidence,
        "method": {"admin_verified": "Administrator verification", "reporter_confirmed": "Reporter confirmation",
                   "reporter_disputed": "Reporter dispute"}.get(decisive["method"]) if decisive else None,
        "verified_at": decisive["created_at"] if decisive else None,
        "resolved_at": _iso(last_res),
        "resolved_by": {"team": t["department"], "owner": t["owner"] if t["owner"] not in (None, "", "Unassigned") else None},
        "reopen_count": reopen_count, "dispute_count": len(disputes),
        "last_dispute": dispute_info,
        "possible_recurrence": recurrence,
        "policy": verification_policy(t),
        "lifecycle": lifecycle,
    }


def ticket_verification(ticket_id: str, include_private: bool = False, admin_view: bool = False) -> Optional[Dict[str, Any]]:
    snap = snapshot(force=True)
    t = next((x for x in snap["tickets"] if x["id"] == ticket_id), None)
    if not t:
        return None
    out = {"ticket_id": ticket_id, "title": t["title"], "ticket_status": t["status"],
           **verification_for(t, snap["tickets"], snap["loaded_at"], include_private, admin_view=admin_view)}
    if include_private and out["last_dispute"] and out["last_dispute"]["has_image"]:
        conn, engine = get_connection()
        cur = conn.cursor()
        ph = "%s" if engine == "postgresql" else "?"
        cur.execute(f"SELECT image FROM resolution_verifications WHERE id = {ph}", (out["last_dispute"]["verification_id"],))
        row = cur.fetchone()
        conn.close()
        out["last_dispute"]["image"] = (row["image"] if isinstance(row, dict) else row[0]) if row else None
    return out


def record_verification(ticket_id: str, method: str, actor: str, note: Optional[str], image: Optional[str],
                        reason: Optional[str] = None) -> None:
    conn, engine = get_connection()
    cur = conn.cursor()
    ph = "%s" if engine == "postgresql" else "?"
    now = _now().isoformat()
    cur.execute(f"INSERT INTO resolution_verifications (ticket_id, method, actor, note, image, created_at, reason) VALUES ({ph},{ph},{ph},{ph},{ph},{ph},{ph})",
                (ticket_id, method, actor, note, image, now, reason))
    action = {"admin_verified": "Resolution verified by administrator",
              "reporter_confirmed": "Reporter confirmed resolution",
              "reporter_disputed": f"Reporter disputed resolution: {DISPUTE_REASONS.get(reason or '', 'problem still exists')}"}[method]
    cur.execute(f"INSERT INTO activity_logs (ticket_id, action, actor, created_at, notes) VALUES ({ph},{ph},{ph},{ph},{ph})",
                (ticket_id, action, actor, now, note))
    conn.commit()
    conn.close()
    invalidate()


class ReverificationError(Exception):
    def __init__(self, status: int, message: str):
        super().__init__(message)
        self.status = status


def reporter_respond(ticket_id: str, token: Optional[str], confirmed: bool, reason: Optional[str],
                     note: Optional[str], image: Optional[str]) -> Dict[str, Any]:
    """Server-authoritative reporter decision. One response per resolution cycle."""
    if not check_reporter_token(ticket_id, token):
        raise ReverificationError(403, "Only the person who reported this ticket can verify its resolution on this device.")
    snap = snapshot(force=True)
    t = next((x for x in snap["tickets"] if x["id"] == ticket_id), None)
    if not t:
        raise ReverificationError(404, f"Ticket {ticket_id} not found")
    if t["status"] not in CLOSED:
        raise ReverificationError(400, "This ticket is not marked resolved, so there is nothing to verify yet.")
    v = verification_for(t, snap["tickets"], snap["loaded_at"], has_credential=True)
    if not v["reporter_can_respond"]:
        raise ReverificationError(409, "You have already responded to this resolution.")
    if sum(1 for x in t["verifications"] if x["method"].startswith("reporter")) >= MAX_REPORTER_RESPONSES:
        raise ReverificationError(429, "This ticket has reached the maximum number of reverification responses. Operations will follow up directly.")
    if not confirmed and reason not in DISPUTE_REASONS:
        raise ReverificationError(400, "Please choose what is still wrong.")

    if confirmed:
        record_verification(ticket_id, "reporter_confirmed", "Reporter", note, None)
    else:
        record_verification(ticket_id, "reporter_disputed", "Reporter", note, image, reason)
        # Return to the existing operational workflow — visibly, with a reason, never silently.
        update_ticket_record(ticket_id, {"status": "In Progress",
                                         "comment": f"Returned for review after reporter dispute ({DISPUTE_REASONS[reason]})."},
                             actor="KAIROS Reverification")
    invalidate()
    return ticket_verification(ticket_id, include_private=True)


def request_reverification(ticket_id: str) -> bool:
    """Called after a ticket enters Resolved/Closed. Logs the request once per cycle when a reporter can respond."""
    snap = snapshot(force=True)
    t = next((x for x in snap["tickets"] if x["id"] == ticket_id), None)
    if not t or t["status"] not in CLOSED or not t.get("has_credential"):
        return False
    last_res = (_resolution_times(t) or [None])[-1]
    if last_res and any(l["action"].startswith("Reporter reverification requested") and l["at"] and l["at"] >= last_res for l in t["logs"]):
        return False
    conn, engine = get_connection()
    cur = conn.cursor()
    ph = "%s" if engine == "postgresql" else "?"
    cur.execute(f"INSERT INTO activity_logs (ticket_id, action, actor, created_at) VALUES ({ph},{ph},{ph},{ph})",
                (ticket_id, "Reporter reverification requested (in-app)", "KAIROS", _now().isoformat()))
    conn.commit()
    conn.close()
    invalidate()
    return True


def reporter_tickets(pairs: List[Dict[str, str]]) -> List[Dict[str, Any]]:
    """Status of the tickets this device reported. Pairs with a wrong token are silently skipped."""
    snap = snapshot()
    by_id = {t["id"]: t for t in snap["tickets"]}
    out = []
    for p in pairs[:50]:
        tid = (p.get("ticket_id") or "").upper()[:30]
        t = by_id.get(tid)
        if not t or not check_reporter_token(tid, p.get("token")):
            continue
        v = verification_for(t, snap["tickets"], snap["loaded_at"], include_private=True, has_credential=True)
        out.append({"ticket_id": tid, "title": t["title"], "location": t["location"], "status": t["status"],
                    "verification_status": v["status"], "state": v["state"], "reporter_can_respond": v["reporter_can_respond"],
                    "resolved_at": v["resolved_at"], "resolved_by": v["resolved_by"], "policy": v["policy"],
                    "last_dispute": v["last_dispute"], "verified_at": v["verified_at"]})
    return out


def _memory_verification(t: Dict, tickets: List[Dict], now: datetime) -> Dict[str, Any]:
    v = verification_for(t, tickets, now)
    confirmed = next((x for x in t["verifications"] if x["method"] == "reporter_confirmed"), None)
    return {"verification": v["status"], "verified_at": v["verified_at"],
            "reporter_confirmed": bool(confirmed), "reopen_count": v["reopen_count"],
            "dispute_reason": v["last_dispute"]["reason_label"] if v["last_dispute"] else None,
            "possible_recurrence": [r["ticket_id"] for r in v["possible_recurrence"]]}


def campus_memory(snap: Dict[str, Any], ticket_id: Optional[str] = None, building: Optional[str] = None,
                  category: Optional[str] = None, query: Optional[str] = None) -> Dict[str, Any]:
    tickets, now = snap["tickets"], snap["loaded_at"]
    anchor = None
    if ticket_id:
        anchor = next((t for t in tickets if t["id"] == ticket_id.upper()), None)
        if not anchor:
            return {"found": False, "message": f"Ticket {ticket_id.upper()} not found.", "incidents": []}
        building, category = anchor["building"], anchor["category"]
    if building:
        building = resolve_building(building)[0]
    q = (query or "").lower().strip()

    def match(t):
        if anchor and t["id"] == anchor["id"]:
            return False
        if building and t["building"] != building:
            return False
        if category and t["category"].lower() != category.lower():
            return False
        if q and q not in f"{t['title']} {t['location']} {t['summary']}".lower():
            return False
        return t["status"] in CLOSED

    past = sorted([t for t in tickets if match(t)], key=lambda t: t["created"], reverse=True)
    items = []
    for t in past[:25]:
        resolution = t["notes"][-1]["action"][6:] if t["notes"] else None
        items.append({
            "id": t["id"], "title": t["title"], "date": _iso(t["created"]), "location": t["location"],
            "building": t["building"], "category": t["category"], "department": t["department"],
            "owner": t["owner"], "resolution": resolution or "No resolution note recorded",
            "duration_hours": _hours(t["closed_at"] - t["created"]) if t["closed_at"] else None,
            "within_sla": (t["closed_at"] <= t["due"]) if t["closed_at"] else None,
            **_memory_verification(t, tickets, now),
        })
    durations = [i["duration_hours"] for i in items if i["duration_hours"] is not None]
    scope = " · ".join(x for x in [building, category, f"“{query}”" if query else None] if x) or "all locations"
    if len(items) == 0:
        return {"found": False, "scope": scope, "incidents": [], "message": "Not enough historical data — no resolved incidents match this scope."}
    return {
        "found": True, "scope": scope, "incidents": items, "count": len(past),
        "summary": {
            "count": len(past),
            "median_resolution_hours": sorted(durations)[len(durations) // 2] if durations else None,
            "within_sla": sum(1 for i in items if i["within_sla"]),
            "reporter_verified": sum(1 for i in items if i["reporter_confirmed"]),
            "reopened": sum(i["reopen_count"] for i in items),
            "departments": dict(Counter(i["department"] for i in items)),
            "first_seen": items[-1]["date"], "last_seen": items[0]["date"],
        },
        "message": None if len(past) >= 3 else "Limited history — fewer than 3 resolved incidents match; treat patterns with caution.",
    }


# ---------------------------------------------------------------------------
# Overview for the War Room (single cached call)
# ---------------------------------------------------------------------------

def overview() -> Dict[str, Any]:
    snap = snapshot()
    tickets, now = snap["tickets"], snap["loaded_at"]
    signals = detect_signals(snap)
    warnings = early_warnings(snap, signals)
    open_t = [t for t in tickets if t["status"] in OPEN]
    risks = sla_risks(snap)
    by_building: Dict[str, Dict[str, Any]] = {}
    for b, cfg in BUILDINGS.items():
        items = [t for t in open_t if t["building"] == b]
        bsig = [s for s in signals if s.get("building") == b or b in buildings_on_line(s["service"], s["line"] or "")]
        by_building[b] = {"building": b, "type": cfg["type"], "zone": cfg["zone"], "open": len(items),
                          "critical": sum(1 for t in items if t["priority"] == "Critical"),
                          "breached": sum(1 for t in items if t["due"] < now),
                          "risk_level": bsig[0]["level"] if bsig else None,
                          "signal_ids": [s["id"] for s in bsig]}
    owners = Counter(t["owner"] for t in open_t if t["owner"] not in (None, "", "Unassigned"))
    since = now - timedelta(hours=24)
    changes = []
    for t in tickets:
        for l in t["logs"]:
            if l["at"] and l["at"] >= since:
                changes.append({"ticket_id": t["id"], "action": l["action"], "actor": l["actor"], "at": _iso(l["at"]), "building": t["building"]})
    changes.sort(key=lambda c: c["at"], reverse=True)
    return {
        "generated_at": now.isoformat(),
        "health": health_report(snap),
        "kpis": {
            "active": len(open_t),
            "critical": sum(1 for t in open_t if t["priority"] == "Critical"),
            "overdue": len(risks["breached"]),
            "approaching_sla": len(risks["approaching"]),
            "emerging_risks": sum(1 for w in warnings if w["state"] == "active" and w["kind"] != "sla"),
            "unassigned": sum(1 for t in open_t if t["owner"] in (None, "", "Unassigned")),
            "response_load": {"staff_engaged": len(owners), "busiest": owners.most_common(1)[0] if owners else None,
                              "avg_per_staff": round(sum(owners.values()) / len(owners), 1) if owners else 0},
        },
        "warnings": warnings,
        "signals": signals[:8],
        "sla": risks,
        "buildings": list(by_building.values()),
        "live_incidents": [_brief(t, now) for t in sorted(open_t, key=lambda t: t["created"], reverse=True)[:12]],
        "recent_changes": changes[:15],
        "graph": incident_graph(snap, signals=signals),
        "topology": TOPOLOGY_VERSION,
        "demo_ticket_ids": demo_ticket_ids(),
        "reverification": _reverification_queue(snap),
        "data_note": "All figures are computed from KAIROS tickets and audit logs; dependencies come from the configured campus topology.",
    }


def _reverification_queue(snap: Dict[str, Any]) -> Dict[str, Any]:
    awaiting, disputed, verified = [], [], 0
    for t in snap["tickets"]:
        v = verification_for(t, snap["tickets"], snap["loaded_at"])
        if v["state"] == "awaiting_reporter":
            awaiting.append({"ticket_id": t["id"], "title": t["title"], "resolved_at": v["resolved_at"], "policy": v["policy"]["level"]})
        elif v["state"] in ("disputed", "disputed_returned"):
            disputed.append({"ticket_id": t["id"], "title": t["title"], "reason": v["last_dispute"]["reason_label"], "at": v["last_dispute"]["at"], "status": t["status"]})
        elif v["state"] == "verified_reporter":
            verified += 1
    return {"awaiting": awaiting, "disputed": disputed, "verified_by_reporter": verified}


def topology() -> Dict[str, Any]:
    return {"version": TOPOLOGY_VERSION, "buildings": [{"name": b, **{k: v for k, v in c.items() if k != "keywords"}} for b, c in BUILDINGS.items()],
            "services": list(SERVICE_LINES.keys()), "lines": SERVICE_LINES}


# ---------------------------------------------------------------------------
# Action workflow: preview (read-only) → confirm → execute through existing write paths
# ---------------------------------------------------------------------------

ACTION_TYPES = ("assign", "escalate", "set_status", "add_note", "reroute", "broadcast", "verify_resolution")


def _describe(a: Dict[str, Any], t: Optional[Dict]) -> str:
    tid = a.get("ticket_id")
    return {
        "assign": f"Assign {tid} to {a.get('owner')}" + (f" (currently {t['owner']})" if t else ""),
        "escalate": f"Escalate {tid} priority {t['priority'] if t else '?'} → {a.get('priority')}",
        "set_status": f"Change {tid} status {t['status'] if t else '?'} → {a.get('status')}",
        "add_note": f"Add operational note to {tid}: “{(a.get('note') or '')[:120]}”",
        "reroute": f"Re-route {tid} {t['department'] if t else '?'} → {a.get('department')}",
        "broadcast": f"Publish {a.get('level', 'warning')} broadcast to {a.get('sector', 'Campus-Wide')}: “{a.get('title')}”",
        "verify_resolution": f"Mark resolution of {tid} as verified",
    }.get(a.get("type"), "Unknown action")


def preview_actions(actions: List[Dict[str, Any]]) -> Dict[str, Any]:
    from .models import StatusEnum, VALID_STATUS_TRANSITIONS, PriorityEnum, DepartmentEnum
    snap = snapshot(force=True)
    by_id = {t["id"]: t for t in snap["tickets"]}
    staff = {n for n, _ in STAFF_DIRECTORY} | {"Unassigned"}
    items = []
    for a in actions[:25]:
        typ = a.get("type")
        t = by_id.get((a.get("ticket_id") or "").upper()) if a.get("ticket_id") else None
        problem = None
        if typ not in ACTION_TYPES:
            problem = "Unsupported action type."
        elif typ != "broadcast" and not t:
            problem = f"Ticket {a.get('ticket_id')} not found."
        elif typ == "assign" and a.get("owner") not in staff:
            problem = "Owner is not in the staff directory."
        elif typ == "escalate":
            try:
                PriorityEnum(a.get("priority"))
                if PRIORITY_RANK[a["priority"]] <= PRIORITY_RANK.get(t["priority"], 0):
                    problem = f"Already {t['priority']} — escalation would not raise priority."
            except ValueError:
                problem = "Invalid priority."
        elif typ == "set_status":
            try:
                if StatusEnum(a.get("status")) not in VALID_STATUS_TRANSITIONS.get(StatusEnum(t["status"]), set()):
                    problem = f"Transition {t['status']} → {a.get('status')} is not allowed."
            except ValueError:
                problem = "Invalid status."
        elif typ == "reroute":
            try:
                DepartmentEnum(a.get("department"))
            except ValueError:
                problem = "Invalid department."
        elif typ == "add_note" and not (a.get("note") or "").strip():
            problem = "Note is empty."
        elif typ == "broadcast" and not ((a.get("title") or "").strip() and (a.get("message") or "").strip()):
            problem = "Broadcast needs a title and message."
        elif typ == "verify_resolution" and t["status"] not in CLOSED:
            problem = f"{t['id']} is {t['status']} — only resolved incidents can be verified."
        items.append({"action": {**a, "ticket_id": t["id"] if t else a.get("ticket_id")},
                      "description": _describe(a, t), "valid": problem is None, "problem": problem})
    return {"items": items, "executable": sum(1 for i in items if i["valid"]),
            "requires_confirmation": True,
            "notice": "Nothing has been changed. Confirm to execute through the standard KAIROS workflow (audit-logged)."}


def execute_actions(actions: List[Dict[str, Any]], actor: str, reason: Optional[str], signal_key: Optional[str],
                    signal_fingerprint: Optional[str]) -> Dict[str, Any]:
    preview = preview_actions(actions)
    results = []
    reason_txt = f" Reason: {reason}" if reason else ""
    for item in preview["items"]:
        a = item["action"]
        if not item["valid"]:
            results.append({"description": item["description"], "ok": False, "error": item["problem"]})
            continue
        typ, tid = a["type"], a.get("ticket_id")
        ok = True
        if typ == "assign":
            ok = update_ticket_record(tid, {"owner": a["owner"], "comment": f"Assigned via Future Engine.{reason_txt}"}, actor=actor)
        elif typ == "escalate":
            ok = update_ticket_record(tid, {"priority": a["priority"], "comment": f"Escalated via Future Engine.{reason_txt}"}, actor=actor)
        elif typ == "set_status":
            ok = update_ticket_record(tid, {"status": a["status"]}, actor=actor)
            if ok and a["status"] in CLOSED:
                request_reverification(tid)
        elif typ == "add_note":
            ok = update_ticket_record(tid, {"comment": a["note"][:2000]}, actor=actor)
        elif typ == "reroute":
            ok = update_ticket_record(tid, {"department": a["department"], "comment": f"Re-routed via Future Engine.{reason_txt}"}, actor=actor)
        elif typ == "broadcast":
            create_broadcast_alert({"title": a["title"][:200], "message": a["message"][:2000], "level": a.get("level", "warning"),
                                    "sector": (a.get("sector") or "Campus-Wide")[:100]}, creator=actor)
        elif typ == "verify_resolution":
            record_verification(tid, "admin_verified", actor, a.get("note"), None)
        results.append({"description": item["description"], "ok": bool(ok), "error": None if ok else "Rejected by the ticket workflow."})
    invalidate()
    if signal_key and any(r["ok"] for r in results):
        set_signal_state(signal_key, "actioned", signal_fingerprint or "", actor, reason)
    return {"results": results, "executed": sum(1 for r in results if r["ok"]), "failed": sum(1 for r in results if not r["ok"])}
