SEED_TICKETS = [
    {
        "id": "GRV-1001",
        "title": "Water leak outside CSE Block entrance",
        "description": "Continuous pipe leakage is creating a slip hazard at the high-footfall main entry point of the CSE block.",
        "location": "CSE Block, Ground Floor",
        "category": "Water",
        "priority": "High",
        "department": "Facilities",
        "status": "In Progress",
        "owner": "R. Mahesh",
        "sla_hours": 12,
        "created_offset_hours": 5.7,
        "resolved_at": None,
        "image": "/assets/water-leak.png",
        "summary": "Continuous pipe leakage is creating a slip hazard at a high-footfall entry point.",
        "action": "Isolate the pipe junction, place warning signage, and dispatch plumbing maintenance.",
        "priority_rationale": "Water leakage near primary entry creates immediate slip-and-fall hazard and foundation pooling.",
        "activities": [
            {"action": "Complaint submitted by Student ID 22CSE114", "actor": "Portal Intake", "offset_hours": 5.7},
            {"action": "KAIROS classified as Water / High priority and routed to Facilities", "actor": "KAIROS", "offset_hours": 5.6},
            {"action": "Assigned to technician R. Mahesh", "actor": "Admin Desk", "offset_hours": 4.5},
            {"action": "Technician marked the issue In Progress and isolated valve", "actor": "R. Mahesh", "offset_hours": 2.0}
        ]
    },
    {
        "id": "GRV-1002",
        "title": "Streetlight not working near hostel walkway",
        "description": "The primary pedestrian walkway between North Hostel and Central Library has 2 unlit light poles, creating poor visibility at night.",
        "location": "North Hostel Walkway",
        "category": "Electrical",
        "priority": "Medium",
        "department": "Electrical Maintenance",
        "status": "Assigned",
        "owner": "S. Ramesh",
        "sla_hours": 24,
        "created_offset_hours": 7.5,
        "resolved_at": None,
        "image": None,
        "summary": "Walkway lighting is required before evening pedestrian traffic begins.",
        "action": "Inspect fixture, breaker connection, and replace blown LED array.",
        "priority_rationale": "Pedestrian safety concern during nighttime hours.",
        "activities": [
            {"action": "Complaint submitted via web portal", "actor": "Portal Intake", "offset_hours": 7.5},
            {"action": "KAIROS routed issue to Electrical Maintenance", "actor": "KAIROS", "offset_hours": 7.4},
            {"action": "Assigned to S. Ramesh", "actor": "Supervisor", "offset_hours": 5.0}
        ]
    },
    {
        "id": "GRV-1003",
        "title": "Blocked fire exit door in workshop bay",
        "description": "Heavy wooden crates and scrap metal pallets are stacked directly in front of the emergency egress door in Bay 2.",
        "location": "Mechanical Workshop, Bay 2",
        "category": "Security",
        "priority": "Critical",
        "department": "Security",
        "status": "New",
        "owner": "Unassigned",
        "sla_hours": 2,
        "created_offset_hours": 6.2,
        "resolved_at": None,
        "image": None,
        "summary": "Obstruction of a marked emergency exit represents an immediate safety compliance violation.",
        "action": "Clear the exit passage immediately and issue safety compliance notice.",
        "priority_rationale": "Life safety code violation; immediate clearance required.",
        "activities": [
            {"action": "Critical safety hazard reported by lab assistant", "actor": "Portal Intake", "offset_hours": 6.2},
            {"action": "KAIROS flagged CRITICAL safety risk and alerted security head", "actor": "KAIROS", "offset_hours": 6.1}
        ]
    },
    {
        "id": "GRV-1004",
        "title": "Overflowing waste bins near cafeteria",
        "description": "Large garbage bin next to outdoor seating is overflowing with food containers and attracting flies.",
        "location": "Central Cafeteria",
        "category": "Sanitation",
        "priority": "Low",
        "department": "Housekeeping",
        "status": "Resolved",
        "owner": "K. Srilatha",
        "sla_hours": 48,
        "created_offset_hours": 26.0,
        "resolved_at": "Yesterday, 14:38",
        "image": None,
        "summary": "Waste collection needed to maintain hygiene near student dining area.",
        "action": "Dispatch waste collection team and schedule supplementary lunch-hour clearance.",
        "priority_rationale": "Sanitation and dining area hygiene maintenance.",
        "activities": [
            {"action": "Grievance submitted", "actor": "Portal Intake", "offset_hours": 26.0},
            {"action": "Assigned to K. Srilatha", "actor": "Housekeeping Desk", "offset_hours": 25.5},
            {"action": "Resolved with waste clearance and sanitization confirmation", "actor": "K. Srilatha", "offset_hours": 23.8}
        ]
    },
    {
        "id": "GRV-1005",
        "title": "Broken window latch causing draft",
        "description": "2nd floor window latch is snapped off, causing window pane to bang during wind.",
        "location": "North Hostel Walkway",
        "category": "Infrastructure",
        "priority": "Medium",
        "department": "Facilities",
        "status": "In Progress",
        "owner": "R. Mahesh",
        "sla_hours": 24,
        "created_offset_hours": 10.0,
        "resolved_at": None,
        "image": None,
        "summary": "Damaged window hardware causing noise and weather exposure.",
        "action": "Replace sash lock and inspect rubber weather seals.",
        "priority_rationale": "Prevents glass breakage during stormy weather.",
        "activities": [
            {"action": "Complaint submitted", "actor": "Portal Intake", "offset_hours": 10.0},
            {"action": "Assigned to R. Mahesh", "actor": "Facilities Desk", "offset_hours": 8.0}
        ]
    },
    {
        "id": "GRV-1006",
        "title": "Wi-Fi access point down in reading room",
        "description": "Students unable to connect to eduroam in the quiet study wing on 1st floor.",
        "location": "Central Library, Reading Room",
        "category": "Network",
        "priority": "High",
        "department": "IT Infrastructure",
        "status": "Assigned",
        "owner": "A. Sharma",
        "sla_hours": 12,
        "created_offset_hours": 7.0,
        "resolved_at": None,
        "image": None,
        "summary": "Access point failure affecting digital study resources in high-density library zone.",
        "action": "Reboot PoE switch port and check RADIUS authentication logs.",
        "priority_rationale": "High-impact academic disruption during exam revision period.",
        "activities": [
            {"action": "Report submitted by library staff", "actor": "Portal Intake", "offset_hours": 7.0},
            {"action": "KAIROS routed to IT Infrastructure with High priority", "actor": "KAIROS", "offset_hours": 6.9},
            {"action": "Assigned to network engineer A. Sharma", "actor": "IT Helpdesk", "offset_hours": 5.0}
        ]
    },
    {
        "id": "GRV-1007",
        "title": "Ceiling fan sparking in classroom 204",
        "description": "Fan regulator sparks when toggled to speed 4 and emits burning odor.",
        "location": "CSE Block, 2nd Floor Labs",
        "category": "Electrical",
        "priority": "Critical",
        "department": "Electrical Maintenance",
        "status": "In Progress",
        "owner": "S. Ramesh",
        "sla_hours": 2,
        "created_offset_hours": 1.25,
        "resolved_at": None,
        "image": None,
        "summary": "Active electrical arcing hazard inside occupied instructional classroom.",
        "action": "Trip classroom sub-breaker, isolate regulator, and replace switchboard module.",
        "priority_rationale": "Immediate fire and shock hazard.",
        "activities": [
            {"action": "Urgent grievance submitted by faculty", "actor": "Portal Intake", "offset_hours": 1.25},
            {"action": "KAIROS marked CRITICAL and triggered emergency electrical dispatch", "actor": "KAIROS", "offset_hours": 1.2},
            {"action": "S. Ramesh dispatched on-site", "actor": "Supervisor", "offset_hours": 0.8}
        ]
    },
    {
        "id": "GRV-1008",
        "title": "Unsanitary washroom 1st floor boys hostel",
        "description": "Clogged floor drain causing standing water across shower cubicles.",
        "location": "South Hostel Block B, Floor 1",
        "category": "Sanitation",
        "priority": "High",
        "department": "Housekeeping",
        "status": "New",
        "owner": "Unassigned",
        "sla_hours": 12,
        "created_offset_hours": 9.0,
        "resolved_at": None,
        "image": None,
        "summary": "Stagnant drainage water creating hygiene hazard in student residence.",
        "action": "Clear main drain blockage and execute deep chemical sanitization.",
        "priority_rationale": "High health and hygiene impact in residential quarters.",
        "activities": [
            {"action": "Hostel grievance logged", "actor": "Portal Intake", "offset_hours": 9.0}
        ]
    },
    {
        "id": "GRV-1009",
        "title": "Damaged wooden benches in sports lawn",
        "description": "Splintered wood slats on bench near the basketball court.",
        "location": "Sports Complex & Gymnasium",
        "category": "Infrastructure",
        "priority": "Low",
        "department": "Facilities",
        "status": "Closed",
        "owner": "K. Anand",
        "sla_hours": 48,
        "created_offset_hours": 52.0,
        "resolved_at": "2 days ago",
        "image": None,
        "summary": "Outdoor seating requires carpentry repair.",
        "action": "Replace damaged wooden slats and apply weatherproof sealant.",
        "priority_rationale": "Routine campus amenity maintenance.",
        "activities": [
            {"action": "Report submitted", "actor": "Portal Intake", "offset_hours": 52.0},
            {"action": "Repaired and verified by K. Anand", "actor": "K. Anand", "offset_hours": 46.0}
        ]
    },
    {
        "id": "GRV-1010",
        "title": "Main gate barrier sensor stuck open",
        "description": "Vehicle boom barrier arm is remaining vertical due to optical sensor misalignment.",
        "location": "Main Gate & Security Post",
        "category": "Security",
        "priority": "High",
        "department": "Security",
        "status": "Resolved",
        "owner": "P. Kumar",
        "sla_hours": 12,
        "created_offset_hours": 18.0,
        "resolved_at": "Yesterday, 19:10",
        "image": None,
        "summary": "Campus perimeter entry control compromised by sensor fault.",
        "action": "Realign optical reflector and test automatic vehicle barrier cycle.",
        "priority_rationale": "Access control integrity at campus perimeter.",
        "activities": [
            {"action": "Security guard logged malfunction", "actor": "Portal Intake", "offset_hours": 18.0},
            {"action": "Resolved by P. Kumar", "actor": "P. Kumar", "offset_hours": 14.5}
        ]
    },
    {
        "id": "GRV-1011",
        "title": "Low water pressure in 3rd floor labs",
        "description": "Distilled water taps and condenser outlets in Chemistry lab have insufficient pressure.",
        "location": "CSE Block, 2nd Floor Labs",
        "category": "Water",
        "priority": "Medium",
        "department": "Facilities",
        "status": "Assigned",
        "owner": "R. Mahesh",
        "sla_hours": 24,
        "created_offset_hours": 6.0,
        "resolved_at": None,
        "image": None,
        "summary": "Booster pump pressure drop affecting laboratory water supply.",
        "action": "Check rooftop booster pump relay and filter line intake.",
        "priority_rationale": "Affects ongoing laboratory experiments.",
        "activities": [
            {"action": "Complaint submitted by Lab Technician", "actor": "Portal Intake", "offset_hours": 6.0},
            {"action": "Assigned to R. Mahesh", "actor": "Facilities Desk", "offset_hours": 4.5}
        ]
    },
    {
        "id": "GRV-1012",
        "title": "Exposed cable near water cooler",
        "description": "Insulation stripped on power cord feeding the refrigerated water fountain.",
        "location": "Admin Block, Dean Office Corridor",
        "category": "Electrical",
        "priority": "Critical",
        "department": "Electrical Maintenance",
        "status": "In Progress",
        "owner": "S. Ramesh",
        "sla_hours": 2,
        "created_offset_hours": 1.0,
        "resolved_at": None,
        "image": None,
        "summary": "High shock hazard: bare copper cable located adjacent to water supply unit.",
        "action": "Unplug unit from mains, replace 3-core insulated cord, and test Earth leakage breaker.",
        "priority_rationale": "Direct combination of live voltage and water proximity.",
        "activities": [
            {"action": "Hazard submitted by admin staff", "actor": "Portal Intake", "offset_hours": 1.0},
            {"action": "KAIROS classified as CRITICAL and notified S. Ramesh directly", "actor": "KAIROS", "offset_hours": 0.9}
        ]
    },
    {
        "id": "GRV-1013",
        "title": "Stray dog pack near cafeteria entrance",
        "description": "Pack of 4 aggressive stray dogs lingering around food waste bins.",
        "location": "Central Cafeteria",
        "category": "Security",
        "priority": "Medium",
        "department": "Security",
        "status": "Resolved",
        "owner": "P. Kumar",
        "sla_hours": 24,
        "created_offset_hours": 28.0,
        "resolved_at": "Yesterday, 17:00",
        "image": None,
        "summary": "Animal intrusion near student gathering area.",
        "action": "Coordinate with animal welfare shelter and secure cafeteria perimeter gate.",
        "priority_rationale": "Student safety and bite risk mitigation.",
        "activities": [
            {"action": "Grievance logged", "actor": "Portal Intake", "offset_hours": 28.0},
            {"action": "Resolved: Area cleared and gate latch reinforced", "actor": "P. Kumar", "offset_hours": 22.0}
        ]
    },
    {
        "id": "GRV-1014",
        "title": "Projector HDMI cable snapped in Hall 1",
        "description": "Pin broke inside wall-mounted HDMI faceplate in Seminar Hall 1.",
        "location": "CSE Block, Ground Floor",
        "category": "Infrastructure",
        "priority": "Low",
        "department": "IT Infrastructure",
        "status": "Closed",
        "owner": "A. Sharma",
        "sla_hours": 48,
        "created_offset_hours": 40.0,
        "resolved_at": "Yesterday, 11:30",
        "image": None,
        "summary": "Audio-visual interconnect cable damage.",
        "action": "Crimp and terminate new high-speed HDMI wall connector.",
        "priority_rationale": "Standard classroom AV equipment repair.",
        "activities": [
            {"action": "Ticket created", "actor": "Portal Intake", "offset_hours": 40.0},
            {"action": "New cable installed by A. Sharma", "actor": "A. Sharma", "offset_hours": 24.0}
        ]
    },
    {
        "id": "GRV-1015",
        "title": "Water cooler dispensing warm brown water",
        "description": "Rust-tinted water coming from filtration unit in Hostel Block B.",
        "location": "South Hostel Block B, Floor 1",
        "category": "Water",
        "priority": "High",
        "department": "Facilities",
        "status": "New",
        "owner": "Unassigned",
        "sla_hours": 12,
        "created_offset_hours": 4.0,
        "resolved_at": None,
        "image": None,
        "summary": "Contaminated drinking water dispenser poses health hazard to residents.",
        "action": "Shut off inlet valve, replace RO filter cartridges and sediment pre-filter.",
        "priority_rationale": "Potable water quality safety issue.",
        "activities": [
            {"action": "Hostel student logged drinking water complaint", "actor": "Portal Intake", "offset_hours": 4.0},
            {"action": "KAIROS classified as High priority and routed to Facilities", "actor": "KAIROS", "offset_hours": 3.9}
        ]
    },
    {
        "id": "GRV-1016",
        "title": "Elevator stuck between 2nd and 3rd floor",
        "description": "Passenger elevator B halted between floors with doors locked (no passengers inside).",
        "location": "Central Library, Reading Room",
        "category": "Infrastructure",
        "priority": "Critical",
        "department": "Facilities",
        "status": "Resolved",
        "owner": "R. Mahesh",
        "sla_hours": 2,
        "created_offset_hours": 14.0,
        "resolved_at": "Today, 01:30",
        "image": None,
        "summary": "Elevator hoistway interlock tripped; vertical transit suspended.",
        "action": "Manual brake release to nearest floor, OEM elevator technician inspection.",
        "priority_rationale": "High-risk conveyance equipment failure.",
        "activities": [
            {"action": "Security raised elevator fault ticket", "actor": "Security Desk", "offset_hours": 14.0},
            {"action": "OEM technician reset drive and cleared error code", "actor": "R. Mahesh", "offset_hours": 12.5}
        ]
    },
    {
        "id": "GRV-1017",
        "title": "Flickering tube lights in bay 3",
        "description": "Electronic ballast humming loudly and tubes flickering irregularly.",
        "location": "Mechanical Workshop, Bay 2",
        "category": "Electrical",
        "priority": "Low",
        "department": "Electrical Maintenance",
        "status": "New",
        "owner": "Unassigned",
        "sla_hours": 48,
        "created_offset_hours": 14.0,
        "resolved_at": None,
        "image": None,
        "summary": "Fluorescent ballast degradation causing visual fatigue.",
        "action": "Retrofit fixture with direct LED tube lights and bypass ballast.",
        "priority_rationale": "Lighting quality maintenance.",
        "activities": [
            {"action": "Ticket logged", "actor": "Portal Intake", "offset_hours": 14.0}
        ]
    },
    {
        "id": "GRV-1018",
        "title": "Gym treadmill emergency stop broken",
        "description": "Magnetic safety lanyard clip missing and emergency stop button non-responsive on Treadmill #2.",
        "location": "Sports Complex & Gymnasium",
        "category": "Security",
        "priority": "High",
        "department": "Facilities",
        "status": "Assigned",
        "owner": "K. Anand",
        "sla_hours": 12,
        "created_offset_hours": 5.0,
        "resolved_at": None,
        "image": None,
        "summary": "Safety interlock disabled on motorized gym exercise equipment.",
        "action": "Place out-of-order tag, disconnect power plug, and replace emergency switch assembly.",
        "priority_rationale": "Injury risk on high-speed treadmill.",
        "activities": [
            {"action": "Reported by sports instructor", "actor": "Portal Intake", "offset_hours": 5.0},
            {"action": "Assigned to K. Anand", "actor": "Facilities Desk", "offset_hours": 4.0}
        ]
    },
    {
        "id": "GRV-1019",
        "title": "Bio-waste bin cover missing in clinic",
        "description": "Foot pedal broken on medical waste receptacle in campus health dispensary.",
        "location": "Admin Block, Dean Office Corridor",
        "category": "Sanitation",
        "priority": "High",
        "department": "Housekeeping",
        "status": "In Progress",
        "owner": "K. Srilatha",
        "sla_hours": 12,
        "created_offset_hours": 8.0,
        "resolved_at": None,
        "image": None,
        "summary": "Medical waste containment unit cannot be sealed.",
        "action": "Provide replacement foot-pedal bio-hazard bin immediately.",
        "priority_rationale": "Health centre biomedical waste protocol violation.",
        "activities": [
            {"action": "Nurse logged urgent equipment grievance", "actor": "Dispensary Staff", "offset_hours": 8.0},
            {"action": "K. Srilatha delivering replacement bin", "actor": "K. Srilatha", "offset_hours": 4.0}
        ]
    },
    {
        "id": "GRV-1020",
        "title": "Broken door lock on hostel room B-104",
        "description": "Key cylinder is stuck and will not turn from outside or inside.",
        "location": "South Hostel Block B, Floor 1",
        "category": "Security",
        "priority": "High",
        "department": "Hostel Administration",
        "status": "Resolved",
        "owner": "V. Murugan",
        "sla_hours": 12,
        "created_offset_hours": 15.0,
        "resolved_at": "Yesterday, 23:15",
        "image": None,
        "summary": "Resident unable to lock room securely.",
        "action": "Replace mortise lock cylinder and issue 2 new keys to resident.",
        "priority_rationale": "Personal property security and resident safety.",
        "activities": [
            {"action": "Hostel grievance logged", "actor": "Portal Intake", "offset_hours": 15.0},
            {"action": "Lock replaced by V. Murugan", "actor": "V. Murugan", "offset_hours": 12.0}
        ]
    },
    {
        "id": "GRV-1021",
        "title": "AC coolant leak dripping on desks",
        "description": "Split AC indoor unit condensate tray overflowing onto computer table #12.",
        "location": "CSE Block, 2nd Floor Labs",
        "category": "Infrastructure",
        "priority": "Medium",
        "department": "Electrical Maintenance",
        "status": "New",
        "owner": "Unassigned",
        "sla_hours": 24,
        "created_offset_hours": 4.0,
        "resolved_at": None,
        "image": None,
        "summary": "Water dripping directly above electronic lab hardware.",
        "action": "Clear drain pipe blockage and check drain pan tilt angle.",
        "priority_rationale": "Risk of liquid ingress into computer equipment.",
        "activities": [
            {"action": "Grievance submitted by lab assistant", "actor": "Portal Intake", "offset_hours": 4.0}
        ]
    },
    {
        "id": "GRV-1022",
        "title": "Fallen tree branch blocking back walkway",
        "description": "Large branch snapped during heavy storm and is obstructing the cycle path.",
        "location": "North Hostel Walkway",
        "category": "Infrastructure",
        "priority": "Medium",
        "department": "Facilities",
        "status": "In Progress",
        "owner": "R. Mahesh",
        "sla_hours": 24,
        "created_offset_hours": 13.0,
        "resolved_at": None,
        "image": None,
        "summary": "Debris blockage on shared pedestrian and cycling corridor.",
        "action": "Chainsaw branch removal and clear path for cycling.",
        "priority_rationale": "Transit obstruction along student pathway.",
        "activities": [
            {"action": "Ticket logged", "actor": "Portal Intake", "offset_hours": 13.0},
            {"action": "Gardening and grounds crew dispatched", "actor": "R. Mahesh", "offset_hours": 7.0}
        ]
    },
    {
        "id": "GRV-1023",
        "title": "Cafeteria grease trap overflowing",
        "description": "Foul odor and slow drain backup in main commercial kitchen washing bay.",
        "location": "Central Cafeteria",
        "category": "Sanitation",
        "priority": "High",
        "department": "Housekeeping",
        "status": "Assigned",
        "owner": "K. Srilatha",
        "sla_hours": 12,
        "created_offset_hours": 6.0,
        "resolved_at": None,
        "image": None,
        "summary": "Kitchen wastewater drainage impediment.",
        "action": "Pump grease trap interceptor and clear effluent line.",
        "priority_rationale": "Food service operational continuity and sanitation standards.",
        "activities": [
            {"action": "Cafeteria supervisor logged issue", "actor": "Portal Intake", "offset_hours": 6.0},
            {"action": "Assigned to K. Srilatha", "actor": "Housekeeping Desk", "offset_hours": 4.5}
        ]
    },
    {
        "id": "GRV-1024",
        "title": "Library scanner power brick burnt",
        "description": "Document digitization scanner in library reference section will not power on.",
        "location": "Central Library, Reading Room",
        "category": "Network",
        "priority": "Low",
        "department": "IT Infrastructure",
        "status": "Closed",
        "owner": "A. Sharma",
        "sla_hours": 48,
        "created_offset_hours": 45.0,
        "resolved_at": "Yesterday, 16:20",
        "image": None,
        "summary": "Power adapter failure on student document scanner.",
        "action": "Replace 24V 3A DC power adapter and verify scanner optical calibration.",
        "priority_rationale": "Non-critical student service utility.",
        "activities": [
            {"action": "Ticket submitted", "actor": "Portal Intake", "offset_hours": 45.0},
            {"action": "Replaced power supply and verified scan output", "actor": "A. Sharma", "offset_hours": 30.0}
        ]
    },
    {
        "id": "GRV-1025",
        "title": "Emergency exit light battery depleted",
        "description": "Green 'EXIT' emergency luminaire is flashing fault code LED at main gate foyer.",
        "location": "Main Gate & Security Post",
        "category": "Security",
        "priority": "Medium",
        "department": "Security",
        "status": "New",
        "owner": "Unassigned",
        "sla_hours": 24,
        "created_offset_hours": 2.0,
        "resolved_at": None,
        "image": None,
        "summary": "Emergency backup battery backup failure during potential power outage.",
        "action": "Replace Ni-Cd backup battery pack and test automatic test switch.",
        "priority_rationale": "Life safety egress illumination requirement.",
        "activities": [
            {"action": "Security officer logged fault", "actor": "Security Desk", "offset_hours": 2.0}
        ]
    }
]


